services:
  - type: web
    name: kannada-whatsapp-scenarios
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: kannada-whatsapp-db
          property: connectionString

databases:
  - name: kannada-whatsapp-db
    databaseName: kannada_whatsapp
    user: kannada_whatsapp_user
    plan: free 