-- 1. USERS
CREATE TABLE users (
    phone_number TEXT PRIMARY KEY,
    name TEXT,
    current_mode TEXT DEFAULT 'menu',
    current_scenario_id INT,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. SCENARIOS
CREATE TABLE scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    difficulty TEXT,
    bot_persona TEXT NOT NULL,
    situation_seed TEXT NOT NULL,
    opening_line TEXT NOT NULL,
    category TEXT DEFAULT 'General'
);

-- 3. CHAT_HISTORY
CREATE TABLE chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT NOT NULL REFERENCES users(phone_number),
    role TEXT NOT NULL,
    mode TEXT NOT NULL,
    scenario_id INT REFERENCES scenarios(id),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. USER_PROGRESS
CREATE TABLE user_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT NOT NULL REFERENCES users(phone_number),
    scenario_id INT NOT NULL REFERENCES scenarios(id),
    status TEXT DEFAULT 'completed',
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(phone_number, scenario_id)
);

-- 5. INDEXES
CREATE INDEX idx_chat_history_lookup ON chat_history(phone_number, created_at DESC);